name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: xcodebuild test -project XCTestExample.xcodeproj/ -scheme XCTestExample -resultBundlePath TestResults -sdk iphonesimulator 
           \-destination "platform=iOS Simulator,name=iPhone 8"
           \-destination "platform=iOS Simulator,name=iPhone 11"
        
        
      - uses: kishikawakatsumi/xcresulttool@v1.3.0
        with:
          path: TestResults.xcresult
        if: success() || failure()
